from ubuntu:14.04
MAINTAINER Emil Lamm Nielsen

# keep upstart quiet
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -sf /bin/true /sbin/initctl

# no tty
ENV DEBIAN_FRONTEND noninteractive

# get up to date
RUN apt-get update --fix-missing

# global installs [applies to all envs!]
RUN apt-get install -y build-essential git libpq-dev
RUN apt-get install -y python python-dev python-setuptools
RUN apt-get install -y python-pip python-virtualenv
RUN apt-get install -y nginx supervisor
RUN apt-get install -y binutils libpq-dev libproj-dev gdal-bin

# stop supervisor service as we'll run it manually
RUN service supervisor stop

# create a virtual environment and install all depsendecies from pypi
RUN virtualenv /opt/venv
ADD requirements/common.txt /opt/venv/requirements/common.txt
ADD requirements/development.txt /opt/venv/requirements/development.txt
ADD requirements/production.txt /opt/venv/requirements/production.txt
RUN /opt/venv/bin/pip install -r /opt/venv/requirements/production.txt

EXPOSE 80

RUN pip install supervisor-stdout

# file management, everything after an ADD is uncached, so we do it as late as
# possible in the process.
ADD ./supervisord.conf /etc/supervisord.conf
ADD ./nginx.conf /etc/nginx/nginx.conf

# restart nginx to load the config
RUN service nginx stop

ENV PYTHONPATH /opt/app:$PYTHONPATH
ENV DJANGO_SETTINGS_MODULE impaqd_server.settings.production
#ENV PYTHONPATH /d/mercedes-backend/
#ENV DJANGO_SETTINGS_MODULE impaqd_server.settings.development
ENV DJANGO_SETTINGS_MODULE impaqd_server.settings.production
#ENV DATABASE_URL postgis://SAMBUCA:@localhost/tempdb
#ENV DATABASE_URL postgis://imp2dat:FuBar401da@sandboxdb.traansmission.com/traansmissionsandboxdb
#ENV DATABASE_URL postgis://imp2dat:FuBar401da@demodb.traansmission.com/traansmissiondemodb
ENV NOTIFICATION_EMAIL emil@traansmission.com
ENV HOST http://localhost:8000
ENV CERTIFICATE sandbox-prod
ENV CELERY_BROKER_URL amqp://emil:emil1234@ec2-52-6-165-114.compute-1.amazonaws.com:5672//
#ENV CELERY_BROKER_URL amqp://traansrabbit:IpaApi101ra@messages-sandbox.services.traansmission.com:5672//
ENV SECRET_KEY 1234567
ENV POSTGIS_VERSION 2 1
ENV TEST_DATABASE_URL postgis://SAMBUCA:@localhost/traansmission-test
ENV PORTAL_URL http://localhost:9000/#/
ENV AWS_ACCESS_KEY_ID AKIAJ2BKKRRUGO6ZKQFQ
ENV AWS_SECRET_ACCESS_KEY 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
ENV S3_BUCKET_PREFIX local-emil
ENV DEBUG true
ENV TOS_CURRENT_VERSION 1

# deploy code
ADD . /opt/app

# start supervisor to run our wsgi server
#CMD supervisord -c /etc/supervisord.conf -n

COPY ./docker-entrypoint.sh /opt
ENTRYPOINT ["/opt/docker-entrypoint.sh"]